var SUB_CODE_CONF={
	"shsq":"ltmclub",
	"stkclub":"ltmclub",
	"ltqqclub":"ltmclub",
	"wdylc":"ltmclub",
	"sjclub":"ltmclub",
	"ddclub":"ltmclub",
	"txclub":"ltmclub",
	"ptkclub":"ltmclub",
	"ltgzly":"ltmclub", 
	"qwshsq":"ltmclub",
	"ltmclub":"ltmclub",
	"ltmts":"ltmclub",
	"ltcyclub":"ltmclub",
	'cjclub':'ltmclub',
	
	"cjhyiap":"clubiap",
	"cjhytiap":"clubiap",
	"clubiap":"ltmclub", 
	"chzziap":"clubiap",
	"ycjhyiap":"clubiap",
	"yclubiap":"clubiap",
	
	"nfjzgw":"xxjzgw",
	"xxjzgw":"xxjzgw",
	"-qzonewap":"xxjzgw",
	"qwxxjzgw":"xxjzgw",
	"ltwxclub":"xxjzgw",
	"hzios":"xxjzgw",
	"qzyxc":"xxjzgw",
	"xxkj15zz":"xxjzgw",
	"hzyxjd":"xxjzgw",
	"xxjzsj":"xxjzsj",
	"xxqqf":"xxqqf",
	"wdssx":"xxqqf",
	"xxqqf30":"xxqqf",
	"nfqqf":"xxqqf",
	"shqx":"xxqqf",
	"qqshow":"xxqqf",
	"xxzxyy":"xxzxyy",
	"xxzxsj":"xxzxyy",
	"xxzxhh":"xxzxyy",
	"xxyyby":"xxzxyy",
	"xxmusic":"xxzxyy",
	"lzmdo":"xxzxyy",
	"xxyysj":"xxzxyy",
	"xxsong":"xxzxyy",
	"ykyyhy":"xxzxyy",
	"nfzxyy":"xxzxyy",
	"xxyy15wd":"xxzxyy",
	"xxyy15zz":"xxzxyy",
	"xxyyrl":"xxzxyy",
	"yyhy":"xxzxyy",
	"wdyyhy":"xxzxyy",
	"qwyyhy":"xxzxyy",
	"wdylwx":"xxzxyy",
	"zzxyydd":"xxzxyy",
	"lziap":"lziap",
	"xxqgame":"xxqgame",
	"xxqqgame":"xxqgame",
	"wdjydd":"xxqgame",
	"xxzhbh":"xxqgame",
	"qwxxqgame":"xxqgame",
	"yxxyqh":"xxqgame",
	"wdyxms":"xxqgame",
	"nfqgame":"xxqgame",
	"xxzxgj":"xxzxgj",
	"xxzxgp":"xxzxgp",
	"petvip":"petvip",
	"qqpetwx":"petvip",
	"dnfhz":"dnfhz",
	"qqfczz":"qqfczz",
	"qqfchh":"qqfczz",
	"fczzzz":"qqfczz",
	"qqxwzz":"qqxwzz",
	"xxvip":"xxvip",
	"cfclub":"cfclub",
	"qqr2by":"qqr2by",
	"xxqqt":"xxqqt",
	"magpt":"qqbookby",
	"bookclub":"qqbookby",
	"qqbookby":"qqbookby",
	"qqyfsc":"qqbookby",
	"qqydiap":"qqydiap",
	"xxsqqm":"xxsqqm",
	"xxsqqy":"xxsqqm",
	"kdxxsqq":"xxsqqm",
	"yksjjlb":"xxsqqm",
	"xxsqq":"xxsqqm",
	"qwxxsqq":"xxsqqm",
	"ykxsqq":"xxsqqm",
	"xxsqqmdo":"xxsqqm",
	"avavip":"avavip",
	"ltqqx":"ltqqx",
	"lkwg":"lkwg",
	"mzyff":"mzyff",
	"yxqqc":"mzyff",
	"ykmz":"mzyff",
	"mhvip":"mhvip",
	"xyvip":"xyvip",
	"cftvip":"cftvip",
	"qsbyqz":"qsbyqz",
	"nfnbavip":"nbavip",
	"nbavip":"nbavip",
	"qlhz":"xxqqf",
	"qqpacket":"qqpacket",
	"lhby":"qqpacket",
	"xinz":"xinz",
	"-hsvipat":"-hsvipat",
	"czjrby":"czjrby",
	"txsp":"txsp",
    "hlwho":"txsp",
	"dsyqby":"dsyqby",
	"xsby":"xsby",
	"qqxy":"qqxy",
	"wcbydq":"wcbydq",
	"qlyz":"qlyz",
	"nbakdq":"nbakdq",
	"wbclub":"wbclub",
	"weibonf":"wbclub",
	"jjxf":"jjxf",
	"xylmby":"xylmby",
	"qqacct_save":"qqacct_save",
	"-qqpoint":"-qqpoint",
	"fifaby":"fifaby",
	"fifasj":"fifaby",
	"fifahh":'fifaby',
	"qqyfsc":"qqyfsc",
	"lkjlzj":"lkjlzj",
	"qqmsey":"qqmsey",
	"qqmstw":"qqmstw",
    "txtypcby":"txtypcby",
    "cjxzlh": "cjxzlh"
};
function confInstall(dir,price,name,siteLink,siteName)
{
	this.dir=dir;
	this.price=price;
	this.name=name;
	this.siteLink=siteLink;
	this.siteName=siteName;
}
var codeConf={
	"ltmclub":new confInstall("qqvip","10","QQ会员","http://vip.qq.com/","QQ会员"),
    "ltmclhh":new confInstall("qqvip","15","QQ会员豪华版","http://vip.qq.com/","QQ会员"),
	'cjclub':new confInstall("qqvip","20","超级会员","http://vip.qq.com/","QQ会员"),
	'clubiap':new confInstall("qqvip","20","超级会员","http://vip.qq.com/","QQ会员"),
    "ltmts":new confInstall("qqvip","5","QQ会员豪华版","http://vip.qq.com/","QQ会员"),
	"xxjzgw":new confInstall("qzone","10","黄钻贵族","http://vip.qzone.com","QQ空间"),
	"xxjzghh":new confInstall("qzonelux","15","黄钻贵族豪华版","http://vip.qzone.com/supervip.html","QQ空间"),
	"xxjzsj":new confInstall("qzonelux","15","黄钻贵族","http://vip.qzone.com/supervip.html","QQ空间"),
	"hzios":new confInstall("qzone","10","黄钻贵族","http://vip.qzone.com","QQ空间"),
	"xxqqf":new confInstall("qqshow","10","红钻贵族","http://show.qq.com/","QQ秀"),
	"xxqfhh":new confInstall("qqshow","15","红钻贵族豪华版","http://show.qq.com/","QQ秀"),
	"qlhzhh":new confInstall("qqshow","15","红钻贵族","http://show.qq.com/","QQ秀"),
	"qlhz":new confInstall("qqshow","15","红钻贵族","http://show.qq.com/","QQ秀"),
	"xxzxyy":new confInstall("music","10","绿钻贵族","http://vip.music.qq.com/","QQ音乐"),
	"xxzxhh":new confInstall("music","15","绿钻贵族豪华版","http://vip.music.qq.com/","QQ音乐"),
	"xxzxsj":new confInstall("music","15","绿钻贵族豪华版","http://vip.music.qq.com/","QQ音乐"),
	"lziap":new confInstall("music","10","绿钻贵族","http://vip.music.qq.com/","QQ音乐"),
	"xxqgame":new confInstall("qqgame","10","蓝钻贵族","http://gamevip.qq.com/index.shtml?ADTAG=PAY.ZH.ICON","QQ游戏"),
	"xxzxgj":new confInstall("qqgp","15","蓝钻豪华版","http://gamevip.qq.com/hhb/index.shtml?ADTAG=PAY.ZH.ICON","QQ游戏"),
	"xxzxgp":new confInstall("qqgp","15","蓝钻豪华版","http://gamevip.qq.com/hhb/index.shtml?ADTAG=PAY.ZH.ICON","QQ游戏"),
	"dnfhz":new confInstall("dnf","20","DNF黑钻","http://dnf.qq.com/","DNF"),
	"qqfczz":new confInstall("speed","10","飞车紫钻","http://speed.qq.com/","QQ飞车"),
	"fczzzz":new confInstall("speed","10","飞车紫钻豪华版","http://speed.qq.com/","QQ飞车"),
	"petvip":new confInstall("pet","10","粉钻贵族","http://pet.qq.com/","QQ宠物"),
	"qqxwzz":new confInstall("x5","20","炫舞紫钻","http://x5.qq.com/","QQ炫舞"),
	"xxvip":new confInstall("xx","20","寻仙VIP","http://xx.qq.com/","寻仙"),
	"cfclub":new confInstall("cf","30","CF会员","http://cf.qq.com/","穿越火线"),
	"qqr2by":new confInstall("r2","10","音速紫钻","http://r2.qq.com/","QQ音速"),
	"xxqqt":new confInstall("qqtang","10","QQ堂紫钻","http://qqtang.qq.com/","QQ堂"),
	"qqbookby":new confInstall("book","10","读书VIP","http://book.qq.com/lianzaiindex/all/vip1_index_1.htm","腾讯读书"),
	"qqyfsc":new confInstall("book","10","读书VIP","http://book.qq.com/lianzaiindex/all/vip1_index_1.htm","腾讯读书"),
	"xxsqqm":new confInstall("mq","10","超级QQ","http://mq.qq.com/","超级QQ"),
	"ltqqx":new confInstall("qqx","10","QQ行","http://qqx.qq.com/","QQ号码站"),
	"lkwg":new confInstall("roco",10,"洛克王国VIP","http://roco.qq.com/","洛克王国"),
	"avavip":new confInstall("ava",30,"AVA精英","http://ava.qq.com/index.shtml","AVA精英"),
	"mzyff":new confInstall("mz",10,"魔钻","","魔钻"),
	"mhvip":new confInstall("mh",10,"漫画VIP","http://mycomic.qq.com","腾讯动漫"),
	"nbavip":new confInstall("nbavip",10,"NBA会员","http://nbavip.qq.com","NBA会员"),
	"xyvip":new confInstall("qqxy",20,"QQ西游VIP","http://qqxy.qq.com","QQ西游"),
	/*"cftvip":new confInstall("cftvip",15,"财付通VIP","http://vip.tenpay.com","财付通VIP"),*/
	"qqpacket":new confInstall("king",50,"QQ钻皇","http://king.qq.com","QQ钻皇"),
	"qsbyqz":new confInstall("ebook","10","读书VIP","http://qbook.qq.com/","腾讯读书"),
	/*"xinz":new confInstall("xinz","10","心钻","http://qbook.qq.com/","心钻"),*/
	"czjrby":new confInstall("nba2k","20","NBA2KOL全明星","http://nba2k.qq.com","NBA2KOL全明星"),
	/*"-hsvipat":new confInstall("hsvip","30","幻世VIP","http://hxsj.qq.com","幻世VIP"),*/
	"txsp":new confInstall("txsp","20","腾讯视频VIP","http://film.qq.com","腾讯视频VIP"),
    "hlwho":new confInstall("txsp","20","腾讯视频VIP","http://film.qq.com","腾讯视频VIP"),
	"jjxf":new confInstall("jjxf","10","机甲旋风VIP","http://17xf.qq.com","机甲旋风VIP"),
	"wbclub":new confInstall("wbclub","10","微博会员","http://t.qq.com","微博会员"),
	"dsyqby":new confInstall("dsyqby", "6", "读书VIP-原创", "http://yc.qq.com", "腾讯读书"),
	"xsby":new confInstall("xsby", "6", "读书VIP-图书", "http://book.qq.com", "腾讯读书"),
	"qqydiap":new confInstall("xsby", "6", "读书VIP-图书", "http://book.qq.com", "腾讯读书"),
	"xylmby":new confInstall("xylmby", "20", "星影会员", "http://xingying.qq.com", "星影会员"),
	"fifaby":new confInstall("fifaby", "10", "FIFA会员", "http://eafifa.qq.com", "FIFA会员"),
	"lkjlzj":new confInstall("lkjlzj", "10", "精灵战记VIP", "http://17zj.qq.com", "精灵战记VIP"),
	"qqmsey":new confInstall("qqmsey", "8", "音乐随享包", "http://vip.music.qq.com", "QQ音乐"),
	"qqmstw":new confInstall("qqmstw", "12", "豪华音乐随享包", "http://vip.music.qq.com", "QQ音乐"),
    "txtypcby":new confInstall("txtypcby", "30", "腾讯体育会员", "http://kbs.sports.qq.com", "腾讯体育会员"),
    "cjxzlh":new confInstall("cjxzlh", "20", "星钻贵族", "http://xing.qq.com/?aid=jihuotips", "星钻官网"),
	"qqacct_save":new confInstall("qqacct_save","","Q币","",""),
	"-qqpoint":new confInstall("-qqpoint","","Q点","",""),
	
	"dnfdq":new confInstall("dnf","","DNF点券","",""),
	"qqsgpay":new confInstall("sg","","三国点券","",""),
	"xxxy":new confInstall("xx","","仙玉","",""),
	"xwdq":new confInstall("x5","","炫舞点券","",""),
	"avad":new confInstall("ava","","AVA点券","",""),
	"fhzg":new confInstall("zg","","烽火战国点券","",""),
	"ffowy":new confInstall("ffo","","自由幻想彩玉","",""),
	"dmlq":new confInstall("dm","","大明龙权点券","",""),
	"slyx":new confInstall("sl","","丝路币","",""),
	"cfdq":new confInstall("cf","","CF点券","",""),
	"qqkdc":new confInstall("speed","","飞车点券","",""),
	"lszt":new confInstall("qqzt","","绿色征途点券","",""),
	"qqhxsj":new confInstall("hxsj","","幻想世界金子","",""),
	"qxzb":new confInstall("7","","七雄争霸元宝","",""),
	"tmxy":new confInstall("qqxy","","QQ西游元宝","",""),
	"qqxxyb":new confInstall("xxz","","QQ仙侠传元宝","",""),
	"loldq":new confInstall("lol","","英雄联盟点券","",""),
	"qcdd":new confInstall("fight","","斗豆","",""),
	"cjdq":new confInstall("c9","","第九大陆点券","",""),
	"ylzt":new confInstall("yl","","御龙在天金子","",""),
	"qqxjdj":new confInstall("xj","","QQ仙境点券","",""),
	"ttds":new confInstall("tiantang","","天堂点券","",""),
	"wmzb":new confInstall("ba","","文明争霸点券","",""),
	"jjdq":new confInstall("9j","","九界点券","",""),
	"wcbydq":new confInstall("wang","","王朝霸域黄金","",""),
	"qqxy":new confInstall("xy","","轩辕传奇金币","",""),
	"nbakdq":new confInstall("nba2k","","NBA2KOL点券","",""),
	"qqjx":new confInstall("qqjx","","QQ九仙元宝","",""),
	"qiqit":new confInstall("qiqit","","球球堂点券","",""),
	"xzwywb":new confInstall("ss","","星之物语金币","",""),
	"jdbqat":new confInstall("jdbqat","","QQ表情包","",""),
	"mbatsm":new confInstall("mbatsm","","魔法表情包","","")
};
